apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: kimai
type: Opaque
data:
    MYSQL_DATABASE: a2ltYWk=
    MYSQL_USER: a2ltYWk=
    MYSQL_PASSWORD: a2ltYWk=
    MYSQL_ROOT_PASSWORD: VmVkYW50MTIj