apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: kimai
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  hostPath:
    path: /tmp/hostpath-provisioner/default/additional-mysql-data
    type: ""
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: additional-mysql-data
  namespace: kimai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: mysql-pv